version: '3'
services:
  mango:
    container_name: mango
    build: ./servers
    volumes:
      - ./servers/statistics/mango:/tmp
    environment:
      - APP=mango
    ports:
      - "9081:8080"
      - "9881:8081"
  banana:
    container_name: banana
    build: ./servers
    volumes:
      - ./servers/statistics/banana:/tmp
    environment:
      - APP=banana
    ports:
      - "9082:8080"
      - "9882:8081"
  apple:
    container_name: apple
    build: ./servers
    volumes:
      - ./servers/statistics/apple:/tmp
    environment:
      - APP=apple
    ports:
      - "9083:8080"
      - "9883:8081"
  strawberry:
    container_name: strawberry
    build: ./servers
    volumes:
      - ./servers/statistics/strawberry:/tmp
    environment:
      - APP=strawberry
    ports:
      - "9084:8080"
      - "9884:8081"
  orange:
    container_name: orange
    build: ./servers
    volumes:
      - ./servers/statistics/orange:/tmp
    environment:
      - APP=orange
    ports:
      - "9085:8080"
      - "9885:8081"
  flask:
    build: ./loadbalancer
    container_name: loadbalancer
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    depends_on:
      - orange
      - banana
      - strawberry
      - apple
      - mango
    volumes:
      - ./loadbalancer:/loadbalancer
    ports:
      - "5000:5000"
    command: python3 loadbalancer.py